fork_me_ribbon_url: https://github.com/coderefinery/installation
baseurl: "/installation"
title: "Installation instructions"

source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

exclude: ['LICENSE']

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename/
